### ISSUE TITLE
Erron when hosting in Cloudflare with Server Side Rendering enabled

### ISSUE THREAD

**Issue by xabikos** [withastro/adapters#43] opened 2023-07-05 11:53 UTC
### What version of `astro` are you using?

2.7.4

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Firefox

### Describe the Bug

We are using the Server Side Rendering mode with Cloudflare adapter to host our Astro project. We need the SSR mode as we pull the content from the CMS (Storyblok) and to have the live preview it requires Server Side Render pages instead of static generated pages which we are using in production.

While this works fine we have noticed many random errors if we request a page two many times by pressing F5 constantly. When looking into the logs of the cloudflare projects we see the following error

```
{
  "outcome": "exception",
  "scriptName": "pages-worker--1209979-production",
  "exceptions": [
    {
      "name": "Error",
      "message": "The script will never generate a response.",
      "timestamp": 1688555913177
    }
  ],
}
```

which is also described in more details [here](https://zuplo.com/blog/the-script-will-never-generate-a-response-on-cloudflare-workers). Initially we thought that this happens because we fetch data during SSR from an API and something goes wrong there.

When we created a really simple page in Astro that doesn't fetch any content from the CMS and deployed it again we had the same behavior.

We tried both `advanced` and `directory` mode.

### What's the expected result?

Pages should render properly regardless how many times we request them.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tkyzda-4d7fjz?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Soviut** [comment] 2023-10-27 07:02
@dojscart Nice work! This should definitely be reported to Storyblok (if it hasn't already been) and cross linked here.

**Comment by alexanderniebuhr** [comment] 2023-11-07 15:32
AFAICT, this issue is caused by Storyblok. If we can get this confirmed, I would like to close this issue, as we can't fix Storyblock.

**Comment by alexanderniebuhr** [comment] 2023-11-10 07:43
Closing for now, because the Issue seems to be stale. Happy to reopen, if we get new information or confirmation.

**Closed by alexanderniebuhr** 2023-11-10 07:43 UTC
Labels: pkg: cloudflare, upstream, needs response

**Comment by Soviut** [comment] 2023-11-23 18:19
For posterity, a Storyblok dev has said they are aware of the issue and will be looking into fixing it https://github.com/storyblok/storyblok-js-client/issues/682#issuecomment-1824512798

**Comment by jansvabik** [comment] 2024-03-31 16:48
Hi, I've just added a workaround for this issue to the other conversation, hope it helps :) https://github.com/storyblok/storyblok-js-client/issues/682#issuecomment-2028817983
