### ISSUE TITLE
Cloudflare adapter failing to publish function, failed to delete unused files from server bundle

### ISSUE THREAD

**Issue by AVGVSTVS96** [withastro/adapters#257] opened 2024-05-08 06:28 UTC
### Astro Info

```block
Astro                    v4.7.1
Node                     v21.6.1
System                   macOS (arm64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         astro-expressive-code
                         astro-icon
                         @astrojs/react
```

### Describe the Bug

Unable to deploy to cloudflare after switching from static to hybrid rendering with cloudflare adapter.

When deploying I get this error at the very end of the deployment process after upload to cloudflare network completes in log, failing the deployment:
```
Error: Failed to publish your Function. Got error: Uncaught Error: No such module "chunks/prerender_Drxt43jI.mjs". imported from "renderers.mjs"
```

When building my project locally, I now get these errors suggesting files were unable to be deleted from server bundle:
```
02:11:58 
 finalizing server assets 

02:11:58 [build] Rearranging server assets...
02:11:58 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///Users/bassimshahidy/Documents/GitHub/astroSite/dist/_worker.js/chunks/_slug_.2febd4f3_CV4ydC7u.mjs
02:11:58 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///Users/bassimshahidy/Documents/GitHub/astroSite/dist/_worker.js/chunks/_slug_.ac508ade_DkS7nDTy.mjs
02:11:58 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///Users/bassimshahidy/Documents/GitHub/astroSite/dist/_worker.js/chunks/_slug_.c3701bf4_D6HNo8TZ.mjs
02:11:58 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///Users/bassimshahidy/Documents/GitHub/astroSite/dist/_worker.js/chunks/flaskSite.0f2e4fb9_9bFHGqlM.mjs
02:11:58 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///Users/bassimshahidy/Documents/GitHub/astroSite/dist/_worker.js/chunks/gpt.e9ec888a_D8xu0YnI.mjs
02:11:58 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///Users/bassimshahidy/Documents/GitHub/astroSite/dist/_worker.js/chunks/index.44336305_BGQ-1Z0l.mjs
```

Everything worked perfectly when using static generation without cloudflare adapter. 

#### Background on my project
It's an Astro app with a GPT Chat page that uses a cloudflare function to communicate with OpenAI.

This all worked well in static mode. But I wanted to stop using the cloudflare function and switch my site to hybrid mode to handle api communication through a route in Astro.

I switched to hybrid mode and was able to get everything working in dev mode, the route.ts was successfully handling API communication. But when trying to build locally, and deploy to cloudflare I got the above errors.

**I tried deleting the function, but that didn't change anything**, I still get the error that the function failed to be published even though the function no longer existed. There must be something else causing this error?

### What's the expected result?

Should be able to build and deploy without issue.

### Link to Minimal Reproducible Example
Minimal reproduction added. I created a new project, added cloudflare adapter, then created a minimal React button component. Adding the React component reproduced this error.
https://stackblitz.com/github/avgvstvs96/astroMinimalRepro

### Build Log
Here's a copy of the full build log:
```
<pre class="c_c c_bw c_hj c_hk c_nu c_nv c_de c_om c_on c_oo c_op c_fc c_fd c_nw c_by c_oq" style="box-sizing: border-box; border-radius: 0px; color: rgb(217, 217, 217); display: block; font-size: 12px; margin: 0px; overflow: auto; padding: 16px 32px; width: 1141.9px; background-color: rgb(29, 29, 29); border-width: 0px 0px 1px; border-style: solid; border-color: rgb(61, 61, 61) rgb(61, 61, 61) rgb(49, 49, 49); border-image: initial; font-family: monaco, courier, monospace; height: 500px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
02:32:09.356 | Cloning repository...
-- | --
02:32:10.198 | From https://github.com/AVGVSTVS96/astroSite
02:32:10.199 | * branch            e4e55f3130f33bbe9610ce97890b90e71b6bb975 -> FETCH_HEAD
02:32:10.199 |  
02:32:10.251 | HEAD is now at e4e55f3 recreate lock files
02:32:10.252 |  
02:32:10.359 |  
02:32:10.360 | Using v2 root directory strategy
02:32:10.391 | Success: Finished cloning repository files
02:32:12.241 | Checking for configuration in a wrangler.toml configuration file (BETA)
02:32:12.242 |  
02:32:12.361 | No wrangler.toml file found. Continuing.
02:32:13.347 | Detected the following tools from environment: bun@1.1.7, yarn@3.6.3, nodejs@18.17.1
02:32:13.348 | Installing bun 1.1.7
02:32:13.495 | Downloading Bun v1.1.7...
02:32:14.478 | Archive:  /tmp/asdf-bun.HXIo/bun.zip
02:32:15.202 | inflating: /opt/buildhome/.asdf/downloads/bun/1.1.7/bun
02:32:15.274 | Installing Bun v1.1.7...
02:32:15.398 | Bun v1.1.7 is installed successfully!
02:32:15.908 | Installing project dependencies: bun install --frozen-lockfile
02:32:16.199 | bun install v1.1.7 (b0b7db5c)
02:32:22.390 |  
02:32:22.391 | + @tailwindcss/typography@0.5.13
02:32:22.391 | + prettier@3.2.5
02:32:22.391 | + prettier-plugin-astro@0.13.0
02:32:22.391 | + prettier-plugin-tailwindcss@0.5.14
02:32:22.391 | + tailwindcss@3.4.3
02:32:22.392 | + type-coverage@2.28.2
02:32:22.392 | + wrangler@3.53.1
02:32:22.392 | + @ai-sdk/openai@0.0.9
02:32:22.392 | + @astrojs/check@0.5.10
02:32:22.392 | + @astrojs/cloudflare@10.2.5
02:32:22.392 | + @astrojs/react@3.3.2
02:32:22.393 | + @astrojs/tailwind@5.1.0
02:32:22.393 | + @avgvstvs96/remark-sectionize@2.0.0
02:32:22.393 | + @fontsource-variable/inter@5.0.18
02:32:22.393 | + @radix-ui/react-dialog@1.0.5
02:32:22.393 | + @radix-ui/react-dropdown-menu@2.0.6
02:32:22.394 | + @radix-ui/react-icons@1.3.0
02:32:22.394 | + @radix-ui/react-navigation-menu@1.1.4
02:32:22.394 | + @radix-ui/react-select@2.0.0
02:32:22.394 | + @radix-ui/react-slot@1.0.2
02:32:22.394 | + @radix-ui/react-tooltip@1.0.7
02:32:22.394 | + @types/react@18.3.1
02:32:22.394 | + @types/react-dom@18.3.0
02:32:22.395 | + ai@3.1.1
02:32:22.395 | + astro@4.7.1
02:32:22.395 | + astro-expressive-code@0.35.3
02:32:22.395 | + astro-icon@1.1.0
02:32:22.395 | + class-variance-authority@0.7.0
02:32:22.395 | + clsx@2.1.1
02:32:22.396 | + cmdk@1.0.0
02:32:22.396 | + lucide-react@0.368.0
02:32:22.396 | + openai@4.42.0
02:32:22.396 | + react@18.3.1
02:32:22.396 | + react-dom@18.3.1
02:32:22.396 | + sharp@0.33.3
02:32:22.396 | + tailwind-merge@2.3.0
02:32:22.397 | + tailwindcss-animate@1.0.7
02:32:22.397 | + typescript@5.4.5
02:32:22.397 |  
02:32:22.397 | 756 packages installed [6.20s]
02:32:22.412 | Executing user command: bun run build
02:32:22.709 | $ astro build
02:32:25.819 | 06:32:25 [WARN] The currently selected adapter `@astrojs/cloudflare` is not compatible with the image service "Sharp".
02:32:26.275 | 06:32:26 [build] output: "hybrid"
02:32:26.276 | 06:32:26 [build] directory: /opt/buildhome/repo/dist/
02:32:26.276 | 06:32:26 [build] adapter: @astrojs/cloudflare
02:32:26.276 | 06:32:26 [build] Collecting build info...
02:32:26.276 | 06:32:26 [build] ✓ Completed in 626ms.
02:32:26.278 | 06:32:26 [build] Building hybrid entrypoints...
02:32:32.378 | 06:32:32 [astro-icon] Loaded icons from src/icons
02:32:35.617 | Generated an empty chunk: "pages/image-endpoint.js".
02:32:35.928 | 06:32:35 [vite] ✓ built in 9.62s
02:32:35.929 | 06:32:35 [build] ✓ Completed in 9.65s.
02:32:35.930 |  
02:32:35.931 | building client (vite)
02:32:35.961 | 06:32:35 [vite] transforming...
02:32:39.109 | 06:32:39 [vite] ✓ 1616 modules transformed.
02:32:39.233 | 06:32:39 [vite] rendering chunks...
02:32:39.303 | 06:32:39 [vite] computing gzip size...
02:32:39.321 | 06:32:39 [vite] dist/_astro/ec.3zb7u.js                        2.31 kB
02:32:39.321 | 06:32:39 [vite] dist/_astro/ec.zkwn8.css                      16.83 kB │ gzip:  3.88 kB
02:32:39.321 | 06:32:39 [vite] dist/_astro/button.DdHb_GvK.js                 0.09 kB │ gzip:  0.10 kB
02:32:39.322 | 06:32:39 [vite] dist/_astro/ModeToggle.D9B41t1o.js             0.17 kB │ gzip:  0.14 kB
02:32:39.322 | 06:32:39 [vite] dist/_astro/index.8PaMdXXX.js                  0.23 kB │ gzip:  0.18 kB
02:32:39.322 | 06:32:39 [vite] dist/_astro/index.CiJKWFEw.js                  0.38 kB │ gzip:  0.30 kB
02:32:39.322 | 06:32:39 [vite] dist/_astro/ProjectsDropdown.OdLHp64F.js       1.01 kB │ gzip:  0.62 kB
02:32:39.322 | 06:32:39 [vite] dist/_astro/createLucideIcon.B-Zo8CMC.js       1.21 kB │ gzip:  0.57 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/index.C1K8UHFL.js                  1.27 kB │ gzip:  0.64 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/client.Cl6nZA9f.js                 1.59 kB │ gzip:  0.83 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/navLinks.ClH8zCku.js               1.64 kB │ gzip:  0.70 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/index.HTIAZgJA.js                  1.67 kB │ gzip:  0.77 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/ModeToggle.yNOiZpqR.js             2.01 kB │ gzip:  0.91 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/page.BYLdvB6I.js                   2.22 kB │ gzip:  0.98 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/index.oQkIHF6y.js                  4.35 kB │ gzip:  1.56 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/index.BQj4W4z3.js                  7.23 kB │ gzip:  2.91 kB
02:32:39.323 | 06:32:39 [vite] dist/_astro/AccentColorSelector.3yCVNOq6.js    9.68 kB │ gzip:  3.53 kB
02:32:39.324 | 06:32:39 [vite] dist/_astro/SideMenu.Dp89EKhk.js              18.39 kB │ gzip:  6.06 kB
02:32:39.324 | 06:32:39 [vite] dist/_astro/CommandMenu.vpNfeq_1.js           19.27 kB │ gzip:  7.08 kB
02:32:39.324 | 06:32:39 [vite] dist/_astro/DropdownMenu.CqZwYU7C.js          22.94 kB │ gzip:  6.76 kB
02:32:39.324 | 06:32:39 [vite] dist/_astro/button.DHIIfRaC.js                25.16 kB │ gzip:  8.68 kB
02:32:39.324 | 06:32:39 [vite] dist/_astro/index.DVPWPkPO.js                 26.03 kB │ gzip: 10.03 kB
02:32:39.324 | 06:32:39 [vite] dist/_astro/Combination.D8lT3Mkg.js           29.36 kB │ gzip: 10.16 kB
02:32:39.324 | 06:32:39 [vite] dist/_astro/ChatUI.DVEI2ND4.js                45.04 kB │ gzip: 15.99 kB
02:32:39.324 | 06:32:39 [vite] dist/_astro/index.Qsggagnf.js                133.95 kB │ gzip: 43.13 kB
02:32:39.325 | 06:32:39 [vite] ✓ built in 3.38s
02:32:39.627 |  
02:32:39.628 | prerendering static routes
02:32:39.641 | 06:32:39 ▶ src/pages/about.astro
02:32:39.694 | 06:32:39   └─ /about/index.html (+53ms)
02:32:39.695 | 06:32:39 ▶ src/pages/blog.astro
02:32:39.713 | 06:32:39   └─ /blog/index.html (+17ms)
02:32:39.714 | 06:32:39 ▶ src/pages/designProject.astro
02:32:39.725 | 06:32:39   └─ /designProject/index.html (+11ms)
02:32:39.727 | 06:32:39 ▶ src/pages/flaskSite.astro
02:32:39.732 | 06:32:39   └─ /flaskSite/index.html (+5ms)
02:32:39.733 | 06:32:39 ▶ src/pages/gpt.astro
02:32:39.735 | 06:32:39   └─ /gpt/index.html (+2ms)
02:32:39.736 | 06:32:39 ▶ src/pages/gptchat.astro
02:32:39.744 | 06:32:39   └─ /gptchat/index.htmlSelected model: gpt3
02:32:39.762 | (+26ms)
02:32:39.763 | 06:32:39 ▶ src/pages/posts/[...slug].astro
02:32:39.782 | 06:32:39   ├─ /posts/resetwindowspassword/index.html (+18ms)
02:32:39.799 | 06:32:39   ├─ /posts/tailwindregex/index.html (+17ms)
02:32:39.815 | 06:32:39   ├─ /posts/githubcli/index.html (+16ms)
02:32:39.828 | 06:32:39   ├─ /posts/menusbuttonsastro/index.html (+13ms)
02:32:39.850 | 06:32:39   ├─ /posts/astronextgenframework/index.html (+22ms)
02:32:39.871 | 06:32:39   └─ /posts/buildingthissitewithastro/index.html (+21ms)
02:32:39.872 | 06:32:39 ▶ src/pages/react.astro
02:32:39.882 | 06:32:39   └─ /react/index.html (+9ms)
02:32:39.883 | 06:32:39 ▶ src/pages/index.astro
02:32:39.895 | 06:32:39   └─ /index.html (+12ms)
02:32:39.896 | 06:32:39 ✓ Completed in 326ms.
02:32:39.897 |  
02:32:39.897 | generating optimized images
02:32:40.007 | 06:32:40   ▶ /_astro/variableStylesExample.BClHD3bw_Z1YMGxX.webp (before: 109kB, after: 15kB) (+108ms) (1/2)
02:32:40.474 | 06:32:40   ▶ /_astro/astroBackground.3drzIBFT_Z2uHnjX.webp (before: 2990kB, after: 61kB) (+465ms) (2/2)
02:32:40.475 | 06:32:40 ✓ Completed in 578ms.
02:32:40.475 |  
02:32:40.495 | 06:32:40
02:32:40.495 | finalizing server assets
02:32:40.495 |  
02:32:40.495 | 06:32:40 [build] Rearranging server assets...
02:32:40.506 | 06:32:40 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///opt/buildhome/repo/dist/_worker.js/chunks/_slug_.1bfb584f_DkS7nDTy.mjs
02:32:40.506 | 06:32:40 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///opt/buildhome/repo/dist/_worker.js/chunks/_slug_.2fc8440a_D6HNo8TZ.mjs
02:32:40.506 | 06:32:40 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///opt/buildhome/repo/dist/_worker.js/chunks/_slug_.5a7b7383_CV4ydC7u.mjs
02:32:40.506 | 06:32:40 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///opt/buildhome/repo/dist/_worker.js/chunks/flaskSite.44a76617_9bFHGqlM.mjs
02:32:40.507 | 06:32:40 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///opt/buildhome/repo/dist/_worker.js/chunks/gpt.67c7b4a3_D8xu0YnI.mjs
02:32:40.507 | 06:32:40 [WARN] [@astrojs/cloudflare] Issue while trying to delete unused file from server bundle: file:///opt/buildhome/repo/dist/_worker.js/chunks/index.5de6200b_BGQ-1Z0l.mjs
02:32:40.507 | 06:32:40 [build] Server built in 14.86s
02:32:40.508 | 06:32:40 [build] Complete!
02:32:40.593 | Finished
02:32:40.593 | Found _worker.js in output directory. Uploading.
02:32:41.550 | Attaching additional modules:
02:32:41.569 | ┌──────────────────────────────────────────┬──────┬────────────┐
02:32:41.569 | │ Name                                     │ Type │ Size       │
02:32:41.569 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.569 | │ _noop-middleware.mjs                     │ esm  │ 0.12 KiB   │
02:32:41.569 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.570 | │ chunks/_.._C5zdZGD2.mjs                  │ esm  │ 0.19 KiB   │
02:32:41.570 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.570 | │ chunks/about_3EMU4663.mjs                │ esm  │ 0.19 KiB   │
02:32:41.570 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.570 | │ chunks/astro/assets-service_C6IesWTB.mjs │ esm  │ 12.30 KiB  │
02:32:41.570 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.570 | │ chunks/astro_CooeCPsz.mjs                │ esm  │ 88.32 KiB  │
02:32:41.571 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.571 | │ chunks/blog_D7yrM-Wy.mjs                 │ esm  │ 0.19 KiB   │
02:32:41.571 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.571 | │ chunks/chatRoute_CdCNwvA5.mjs            │ esm  │ 0.19 KiB   │
02:32:41.571 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.571 | │ chunks/designProject_DrjGXsKT.mjs        │ esm  │ 0.19 KiB   │
02:32:41.571 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.572 | │ chunks/flaskSite_Cfqmgm42.mjs            │ esm  │ 0.19 KiB   │
02:32:41.572 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.572 | │ chunks/gpt_uGkWc9Dd.mjs                  │ esm  │ 0.19 KiB   │
02:32:41.572 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.572 | │ chunks/gptchat_CPGTWNA3.mjs              │ esm  │ 0.19 KiB   │
02:32:41.572 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.572 | │ chunks/image-endpoint_RvDj3-CK.mjs       │ esm  │ 0.18 KiB   │
02:32:41.573 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.573 | │ chunks/index_WZSNCFiz.mjs                │ esm  │ 0.19 KiB   │
02:32:41.573 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.574 | │ chunks/pages/chatRoute_FUzrq2OS.mjs      │ esm  │ 257.57 KiB │
02:32:41.574 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.575 | │ chunks/pages/image-endpoint_nxDOIah1.mjs │ esm  │ 0.06 KiB   │
02:32:41.575 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.576 | │ chunks/react_BNYkD6qZ.mjs                │ esm  │ 0.19 KiB   │
02:32:41.577 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.578 | │ chunks/vnode-children_D5ZuGMh8.mjs       │ esm  │ 2.95 KiB   │
02:32:41.578 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.578 | │ manifest_DcG7rFFE.mjs                    │ esm  │ 30.43 KiB  │
02:32:41.578 | ├──────────────────────────────────────────┼──────┼────────────┤
02:32:41.579 | │ renderers.mjs                            │ esm  │ 77.29 KiB  │
02:32:41.579 | └──────────────────────────────────────────┴──────┴────────────┘
02:32:41.681 | ✨ Compiled Worker successfully
02:32:41.744 | Found _routes.json in output directory. Uploading.
02:32:41.759 | Validating asset output directory
02:32:42.999 | Deploying your site to Cloudflare's global network...
02:32:48.068 | Uploading... (16/53)
02:32:49.087 | Uploading... (29/53)
02:32:49.335 | Uploading... (41/53)
02:32:49.896 | Uploading... (53/53)
02:32:49.897 | ✨ Success! Uploaded 37 files (16 already uploaded) (2.14 sec)
02:32:49.897 |  
02:32:50.167 | ✨ Upload complete!
02:32:52.382 | Success: Assets published!
02:32:53.399 | Error: Failed to publish your Function. Got error: Uncaught Error: No such module "chunks/prerender_CVkt24g5.mjs".   imported from "renderers.mjs"

</pre>
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment] 2024-05-08 08:42
@AVGVSTVS96 Thanks for letting us know. I think this might be related to a prerendering issue we do have in Astro core, so I don't know how quick a fix can be provided.

**Comment by alexanderniebuhr** [comment] 2024-05-08 08:43
But please add a **minimal** reproduction example instead of your whole project.

**Comment by AVGVSTVS96** [comment] 2024-05-08 13:03
> But please add a **minimal** reproduction example instead of your whole project.

Yes I'll get this done today, thanks!

**Comment by AVGVSTVS96** [comment] 2024-05-08 22:44
@alexanderniebuhr Added minimal example. This error happens after adding any React component to a hybrid rendered Astro site.

https://stackblitz.com/github/avgvstvs96/astroMinimalRepro

**Comment by alexanderniebuhr** [comment] 2024-05-09 05:34
Thank you, it is a duplicate of https://github.com/withastro/adapters/issues/211

**Closed by alexanderniebuhr** 2024-05-09 05:34 UTC
Labels: pkg: cloudflare, upstream, - P4: important, needs repro
