### ISSUE TITLE
Cloudflare Deployment fails, huge worker.js file with large base64 WASM file

### ISSUE THREAD

**Issue by mariusbolik** [withastro/adapters#167] opened 2024-02-14 20:12 UTC
### Astro Info

```block
Astro                    v4.3.7
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             none
```

### Describe the Bug

Hello,

I wanted to deploy my Astro Project to Cloudflare Pages, but I got the following error: Your Functions script is over the 1 MiB size limit

I checked my _worker.js File and saw that it has a file size of over 10MB.

Inside the file I noticed a huge base64 string which seems to be a Web Assembly File. Like 95% of the worker file is the Base64 String.

This is the worker file: [_worker.js.txt](https://github.com/withastro/adapters/files/14285636/_worker.js.txt)

Kind regards,
Marius

### What's the expected result?

Worker with file size under 1 mb.

### Link to Minimal Reproducible Example

https://github.com/mariusbolik/astro-cloudflare

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment] 2024-02-16 07:22
I can not reproduce the issue using your linked repository and running `astro build`.

**Comment by alexanderniebuhr** [comment] 2024-02-29 12:06
Closing this issue due to missing reproduction. If a minimal reproduction is added, I'm happy to reopen this.

**Closed by alexanderniebuhr** 2024-02-29 12:06 UTC
Labels: pkg: cloudflare, needs repro
