### ISSUE TITLE
Deploy to Cloudflare break after update @astrojs/cloudflare to v11 

### ISSUE THREAD

**Issue by mrthiti** [withastro/adapters#305] opened 2024-06-26 05:20 UTC
### Astro Info

```block
Astro                    v4.11.1
Node                     v20.14.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare (v11)
Integrations             @astrojs/lit
```

### Describe the Bug

Step to repoduce:
- Run Astro build (success with no error)
- Deploy to cloudflare page with command 'npx wrangler pages publish'
It error below
![image](https://github.com/withastro/adapters/assets/7018802/18ac86f6-93be-4b16-9081-da5dd8e362a5)

### What's the expected result?

It should deploy to Cloudflare successfully.

### Link to Minimal Reproducible Example

https://youtu.be/5bjwZ6pHsz4?si=dhxHpI6xGYrzld54

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment] 2024-06-26 14:23
@mrthiti You only linked a images as a reproducible example.
Can you please provide your project or a reproducible example. I can't help you, if I don't have a project to run myself.

**Comment by mrthiti** [comment] 2024-06-26 16:13
@alexanderniebuhr I have update link video for reproduce because I can't reproduce on new project.

**Comment by alexanderniebuhr** [comment] 2024-06-26 16:17
Thank you for the quick answer, it's very hard for me to reproduce this without a repository.. Can you share log file, from the location it tells you in the error message please?

**Comment by pthurmond** [comment] 2024-06-29 02:52
So here is an example, I just upgraded my AstroWind-based site to the latest version of AstroWind. When I then upgrade Cloudflare adapter from 9.x to 11.x it no longer builds with `npm run build`.

That repo can be found here: https://github.com/onwidget/astrowind

Like I said, it works with the package set to `"@astrojs/cloudflare": "^9.0.0",` but not with `"@astrojs/cloudflare": "^11.0.1",`.

I just tried it with `^10.0.0` and the build fails with that too. So something was introduced between 9.x and 10.x that is causing it to fail builds. You do your diff there and I think you will find the culprit.

**Comment by pthurmond** [comment] 2024-06-29 02:53
I should add that the error that I was seeing was the following:

`[plugin vite:resolve] Cannot bundle Node.js built-in "fs" imported from "src/utils/config.ts".`

Not the same error, but an issue none the less.

**Comment by chantastic** [comment] 2024-06-29 21:58
hi, i'm also experience an issuer with the v9 to v10/11 upgrade but it seems to be failing for a different reason.

the routes file is completely different between v9 and v10/v11.

```mjs
// astro.config.mjs
import cloudflare from '@astrojs/cloudflare'

export default defineConfig({
    // ...rest
    output: 'hybrid',
    adapter: cloudflare({imageService: 'cloudflare'})
})
```

#### v9 `_routes.json` output

This is as expected. Each of these pages uses `export const prerender = false;`

```json
{
  "version": 1,
  "include": [
    "/_image",
    "/chores/rock",
    "/flip/result",
    "/roll/result",
    "/chores/partials/*"
  ],
  "exclude": []
}
```

#### v10/v11 `_routes.json` output

I'm unsure how this is getting populated but's incorrect and inconsistent with `hybrid/prerender` settings.

```json
{
  "version": 1,
  "include": [
    "/*"
  ],
  "exclude": [
    "/",
    "/_astro/*",
    "/#",
    "/feed/feed.json",
    "/sitemap.xml",
    "/avo",
    "/expensive",
    "/expensive/share",
    "/novimber",
    "/react/concurrent/concurrent-ui-patterns--experimental",
    "/react/concurrent/introducing-concurrent-mode--experimental",
    "/react/concurrent/suspense-for-data-fetching--experimental",
    "/teachable/sales-page-challenge",
    "/lessons",
    "/lessons/marchdown/container-plugin",
    "/lessons/astro/*",
    "/lessons/css/*",
    "/lessons/storybook/*",
    "/lessons/collections",
    "/lessons/epicreact",
    "/lessons/epicreact/a-beginners-guide-to-react",
    "/lessons/epicreact/a-beginners-guide-to-react/01-a-beginners-guide-to-react-introduction",
    "/lessons/epicreact/a-beginners-guide-to-react/02-create-a-user-interface-with-vanilla-javascript-and-dom",
    "/lessons/epicreact/a-beginners-guide-to-react/03-create-a-user-interface-with-reacts-createelement-api",
    "/lessons/epicreact/a-beginners-guide-to-react/04-rendering-children-with-createelement",
    "/lessons/epicreact/a-beginners-guide-to-react/05-create-a-user-interface-with-reacts-jsx-syntax",
    "/lessons/epicreact/a-beginners-guide-to-react/06-use-jsx-effectively-with-react",
    "/lessons/epicreact/a-beginners-guide-to-react/07-render-two-elements-side-by-side-with-react-fragments",
    "/lessons/epicreact/a-beginners-guide-to-react/08-create-a-simple-reusable-react-component",
    "/lessons/epicreact/a-beginners-guide-to-react/09-validate-custom-react-component-props-with-proptypes",
    "/lessons/epicreact/a-beginners-guide-to-react/10-understand-and-use-interpolation-in-jsx",
    "/lessons/epicreact/a-beginners-guide-to-react/11-rerender-a-react-application",
    "/lessons/epicreact/a-beginners-guide-to-react/12-style-react-components-with-classname-and-inline-styles",
    "/lessons/epicreact/a-beginners-guide-to-react/13-use-event-handlers-with-react",
    "/lessons/epicreact/a-beginners-guide-to-react/14-manage-state-in-a-react-component-with-the-usestate-hook",
    "/lessons/epicreact/a-beginners-guide-to-react/15-manage-side-effects-in-a-react-component-with-the-useeffect-hook",
    "/lessons/epicreact/a-beginners-guide-to-react/16-use-a-lazy-initializer-with-usestate",
    "/lessons/epicreact/a-beginners-guide-to-react/17-manage-the-useeffect-dependency-array",
    "/lessons/epicreact/a-beginners-guide-to-react/18-create-reusable-custom-hooks",
    "/lessons/epicreact/a-beginners-guide-to-react/19-manipulate-the-dom-with-react-refs",
    "/lessons/epicreact/a-beginners-guide-to-react/20-understand-the-react-hook-flow",
    "/lessons/epicreact/a-beginners-guide-to-react/21-make-basic-forms-with-react",
    "/lessons/epicreact/a-beginners-guide-to-react/22-make-dynamic-forms-with-react",
    "/lessons/epicreact/a-beginners-guide-to-react/23-controlling-form-values-with-react",
    "/lessons/epicreact/a-beginners-guide-to-react/24-using-react-error-boundaries-to-handle-errors-in-react-components",
    "/lessons/epicreact/a-beginners-guide-to-react/25-use-the-key-prop-when-rendering-a-list-with-react",
    "/lessons/epicreact/a-beginners-guide-to-react/26-lifting-and-colocating-react-state",
    "/lessons/epicreact/a-beginners-guide-to-react/27-make-http-requests-with-react",
    "/lessons/epicreact/a-beginners-guide-to-react/28-handle-http-errors-with-react",
    "/lessons/epicreact/a-beginners-guide-to-react/29-install-and-use-react-devtools",
    "/lessons/epicreact/a-beginners-guide-to-react/30-build-and-deploy-a-react-application-with-codesandbox-github-and-netlify",
    "/lessons/epicreact/a-beginners-guide-to-react/31-a-beginners-guide-to-react-outro",
    "/lessons/epicreact/a-beginners-guide-to-react/outline",
    "/lessons/epicreact/advanced-react-patterns",
    "/lessons/epicreact/advanced-react-patterns/1-0-advanced-react-patterns-welcome",
    "/lessons/epicreact/advanced-react-patterns/2-0-latest-ref",
    "/lessons/epicreact/advanced-react-patterns/6-0-state-reducer",
    "/lessons/epicreact/advanced-react-patterns/6-1-state-reducer_solution",
    "/lessons/epicreact/advanced-react-patterns/6-2--",
    "/lessons/epicreact/advanced-react-patterns/x-0-context-module-functions",
    "/lessons/epicreact/advanced-react-patterns/x-1-context-module-function_solution",
    "/lessons/epicreact/react-fundamentals",
    "/lessons/epicreact/react-fundamentals/1-0-welcome",
    "/lessons/epicreact/react-fundamentals/2-0-basic-js-hello-world",
    "/lessons/epicreact/react-fundamentals/2-1-generate-dom-nodes_solution",
    "/lessons/epicreact/react-fundamentals/2-2-generate-dom-nodes_extra-credit",
    "/lessons/epicreact/react-fundamentals/3-0-intro-to-raw-react",
    "/lessons/epicreact/react-fundamentals/3-1-raw-react-apis_solution",
    "/lessons/epicreact/react-fundamentals/3-2-nested-elements_extra-credit",
    "/lessons/epicreact/react-fundamentals/3-3-break",
    "/lessons/epicreact/react-fundamentals/4-0-using-jsx",
    "/lessons/epicreact/react-fundamentals/4-1-write-markup-with-jsx_solution",
    "/lessons/epicreact/react-fundamentals/4-2-interpolate-classname-and-children_extra-credit",
    "/lessons/epicreact/react-fundamentals/4-3-spread-props_extra-credit",
    "/lessons/epicreact/react-fundamentals/5-0-creating-custom-components",
    "/lessons/epicreact/react-fundamentals/5-1-render-jsx-from-functions_solution",
    "/lessons/epicreact/react-fundamentals/5-2-react-createelement_extra-credit",
    "/lessons/epicreact/react-fundamentals/5-3-jsx_extra-credit",
    "/lessons/epicreact/react-fundamentals/5-4-validation-with-proptypes_extra-credit",
    "/lessons/epicreact/react-fundamentals/5-5-use-prop-types-package_extra-credit",
    "/lessons/epicreact/react-fundamentals/5-6-react-fragments_extra-credit",
    "/lessons/epicreact/react-fundamentals/6-0-styling",
    "/lessons/epicreact/react-fundamentals/6-1-style-prop",
    "/lessons/epicreact/react-fundamentals/6-2-create-a-custom-component_extra-credit",
    "/lessons/epicreact/react-fundamentals/6-3-accept-a-size-prop-to-encapsulate-styling_extra-credit",
    "/lessons/epicreact/react-fundamentals/6-4-break",
    "/lessons/epicreact/react-fundamentals/7-0-forms",
    "/lessons/epicreact/react-fundamentals/7-1-form-basics_solution",
    "/lessons/epicreact/react-fundamentals/7-2-using-refs_extra-credit",
    "/lessons/epicreact/react-fundamentals/7-3-validate-lower-case_extra-credit",
    "/lessons/epicreact/react-fundamentals/7-4-control-the-input-value_extra-credit",
    "/lessons/epicreact/react-fundamentals/8-0-rendering-arrays",
    "/lessons/epicreact/react-fundamentals/8-1-rendering-arrays_solution",
    "/lessons/epicreact/react-fundamentals/8-2-focus-demo_extra-credit",
    "/lessons/epicreact/react-fundamentals/9-0-outro",
    "/lessons/epicreact/welcome",
    "/lessons/epicreact/welcome/1-welcome-to-epic-react",
    "/lessons/epicreact/welcome/2-project-readmes-and-pre-reqs",
    "/lessons/epicreact/welcome/3-clone-and-setup"
  ]
}
```

I read thru the changelog but couldn't find anything that seemed to suggest major changes to the underlying `hybrid/prerender` behavior.

**Comment by alexanderniebuhr** [comment] 2024-06-30 14:03
@chantastic In fact the change in routes generation was introduced in v10, and is actually correct, I wonder why your specific project creates soo many exclude routes though.. Would have to look at a reproduction example

**Comment by chantastic** [comment] 2024-07-01 06:04
@alexanderniebuhr interesting. so, does `export const prerender = false` not apply with this adapter?

**Comment by alexanderniebuhr** [comment] 2024-07-01 06:08
It does, I'm not fully seeing your issue yet. Why is the new `_routes.json` wrong?

**Comment by alexanderniebuhr** [comment] 2024-07-01 06:19
I see the difference in the file, but I don't think it will be an issue for you. There is probably a reason why it chooses the route with `/*` in the `includes` configuration.

Do you get an error when deploying to Cloudflare?

**Comment by chantastic** [comment] 2024-07-01 06:22
I do. Here is a screenshot.

![CleanShot 2024-06-29 at 14 13 01@2x](https://github.com/withastro/adapters/assets/658360/63c09171-61bb-4940-813b-b1ce5ba10036)

(Investigating how to get remove those pages from the list now. but was mostly surprised by the change in `includes`).

**Comment by alexanderniebuhr** [comment] 2024-07-01 06:23
Okay thank you, that helps. I can fix that issue. But to tell you why you get the wildcard in `includes`, I would need to analyze your specific project.

**Comment by chantastic** [comment] 2024-07-01 06:28
thanks for the information. i'll use it to poke around more tomorrow and educate myself. and will report back with anything i missed, or doesn't match expectations.

**Comment by alexanderniebuhr** [comment] 2024-07-01 06:39
@mrthiti I do expect it's the same issue as https://github.com/withastro/astro/issues/10552. Nothing we can fix right now in the adapter, I will keep an eye in core and see how to fix it.. Or if there can be implemented a workaround. Without a real reproduction, this issue isn't really helpful, so I'm going to close it.

**Closed by alexanderniebuhr** 2024-07-01 06:39 UTC
Labels: pkg: cloudflare, upstream
