### ISSUE TITLE
Netlify: Host fails to serve 404 page on failing routes when adapter is in use.

### ISSUE THREAD

**Issue by regisphilibert** [withastro/adapters#133] opened 2024-01-18 19:27 UTC
### Astro Info

```block
Astro                    v4.2.1
Node                     v21.1.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/netlify
Integrations             none
```

### Describe the Bug

The 404 logic of Netlify is broken on a deployed hybrid project. Netlify fails to serve the 404 page (Netlify's or project's own 404.html). See: https://imaginative-pastelito-41792a.netlify.app/notfound

If one tries to enforce the 404 logic by manually adding a redirect rule:

```
# _redirect
/* /404.html 404
```

Then SSR routes (not static) will all land on the provided 404 file.

See https://imaginative-pastelito-41792a.netlify.app/ deployed from minimal repo.

### What's the expected result?

When route is not found Netlify should serve its own 404 page or the project's own 404.html

### Link to Minimal Reproducible Example

https://github.com/regisphilibert/astro-netlify-404-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Skn0tt** [comment] 2024-01-19 08:42
Hey Regis! Thanks for providing the repro. For any page where there's no static asset generated at buildtime, the Netlify adapter is configured to fall back to SSR. SSR seems to render the blank 404 response then. I'd assume that it incorporates `pages/404.astro` when doing that. It doesn't seem like your repro contains a `404.astro` page, what happens if you add it?

**Comment by alexanderniebuhr** [comment] 2024-01-19 16:56
Not sure if that is relevant here, but for Cloudflare there is SPA mode, for which a pre-rendered 404 is needed. SSR 404 pages do not work for Cloudflare and will also return a blank page. Maybe this is related.

**Comment by regisphilibert** [comment] 2024-01-22 19:37
> For any page where there's no static asset generated at buildtime, the Netlify adapter is configured to fall back to SSR

I just realized some of our site would have the SSR functions invoked when someone visited a static route on that project. At first I couldn't understand what was going on since we only have one ssr route and it's only used by CMS editors.

But it turns out, we had a meta in the <head> pointing to local missing files. So the browser would request a 404 on every visit and an ssr function would be invoked. So as you said, whenever someone (or the browser/robots etc...) will hit a 404, the `ssr` function will be triggered. 

It's a bit of a problem considering functions invocations are limited on plans and even though that particular 404 we controlled, it's rarely in our hands who/what will mistype a URL on one of our site. So I don't think it should be taken into take into account in  our monthly limits...

Any way we could simply let the default Netlify 404 behaviour take on here on static routes?

**Comment by Skn0tt** [comment] 2024-01-23 07:53
> Any way we could simply let the default Netlify 404 behaviour take on here on static routes?

For Astro sites with `output: "static"`, this is definitely the default behaviour.

For sites that include server-rendered pages (`output: "server/hybrid"`), we currently use the Astro-generated server code to see if there's a server-rendered page on a route that didn't match a static page before it. This massively simplifies the routing logic, and essentially reuses Astro's routing logic instead of reimplementing it with Netlify mechanisms. The big upside to this is simplicity and correctness, the big downside is that 404 pages are server-rendered.

> [I just added a 404](https://github.com/regisphilibert/astro-netlify-404-repro/commit/7ddbdda1f790d9473a1826378bd2bf9246895157) but like on other projects I've seen the problem on, it has not effect. Still getting a blank response unfortunately.

Interesting! I'll try to reproduce this locally, and see what's going on here that we see a blank response.

**Comment by Skn0tt** [comment] 2024-01-23 08:15
> [I just added a 404](https://github.com/regisphilibert/astro-netlify-404-repro/commit/7ddbdda1f790d9473a1826378bd2bf9246895157) but like on other projects I've seen the problem on, it has not effect. Still getting a blank response unfortunately.

I'm seeing that pages with `prerender = false` are properly rendered by the SSR Function, but pages with `prerender = true` get a blank response as you mentioned. I wonder what's the best course of action to fix this - @alexanderniebuhr curious for your thoughts as well. From my perspective, we could either:

1. make `app.render()` return a redirect to `/404`, similar to what's shown in the [SSR routing code example](https://docs.astro.build/en/core-concepts/routing/#modifying-the-slug-example-for-ssr) in the Astro docs
2. make `app.render()` render the `404.astro` page on demand and return that as the response body, even though it has `prerender = true` defined in it.
3. embed the prerendered `404.html` into the SSR function and return that

What do you think?

**Comment by regisphilibert** [comment] 2024-01-23 14:14
> In my experience, Netlifys limits are generous enough that an additional 404 isn't a big deal, but it always depends on the usecase I assume! What kind of site are you working on, and how tight are the limits for you on that?

It is generous, and I suppose we could live with it, but in the context of marketing wouldn't it be "charging for 404s"?

**Comment by Skn0tt** [comment] 2024-01-23 14:24
> It is generous, and I suppose we could live with it, but in the context of marketing wouldn't it be "charging for 404s"?

Yes, it's charging for 404s, because it's traffic like all other traffic. A 404 response comes from a visitor of your site. On the starter tier, 125k function executions/month are included. That's 3 executions per second, wich is more than enough for a personal site.

**Comment by Skn0tt** [comment] 2024-01-23 14:59
No worries, I get your point :D And I agree that it's not obvious at all, especially since the previous version of the Astro adapter behaved differently on this.

> in no way am I suggesting that 404 should be static at all time if you think it's a bad decision.

Well, ideally we'd honor the `prerender` setting on this, as you mention!  Most 404 pages will be fine with static rendering, maybe some will want to do some dynamic stuff on the server to e.g. make recommendations what page the user might have wanted to go to. Point is, both should be possible, and we should definitely fix that.

In addition to that, maybe we could add a callout to the docs on this? I'll open a PR for that.

**Comment by alexanderniebuhr** [comment] 2024-01-23 21:29
@Skn0tt Sorry for the late response. I'm on vacation, but trying to catch up. Some question to clarify and guide you in the right direction:

- You said that **all** routes are served by the ssr function, regardless if they are assets, pre-rendered or any other statics?
-> We do solve this with the Cloudflare adapter, by using a `_routes.json` to not run the ssr function for static stuff. I suggest the same for Netlify, if possible.
- IIRC we decided agains `app.render()` handling this. I don't know for sure, but I'm pretty sure it should be the Adapter's task to handle 404. _Worth double checking in Discord's #dev channel_
- For the question of dynamic or static 404 it should be up to the user. If the user uses `export const prerender = true;`, it should be static. IIRC a `404.html` should be generated in the "output" folder. In theory that should be "routable" by Netlify without hitting the ssr function, at least it is with Cloudflare.

Hope this helps, I'm still monitoring this, but I might be slower to answer

**Comment by Skn0tt** [comment] 2024-01-29 12:00
Hope you're enjoying your vacation! I don't perceive this issue as being super pressing, so please don't feel like you need to monitor this during your vacation. Writing down my reply for you to look at once you're back:

> You said that all routes are served by the ssr function, regardless if they are assets, pre-rendered or any other statics?

No, we're setting [`preferStatic: true`](https://github.com/withastro/adapters/blob/3854812c9bd3558857bb9084668925835dcf4ee0/packages/netlify/src/index.ts#L116), which configures the CDN give precedence to static assets before calling the SSR function. If there's no static asset at the requested path because it will result in a 404, this means it will still go to the SSR handler and it needs to deal with it.

> IIRC we decided agains app.render() handling this. I don't know for sure, but I'm pretty sure it should be the Adapter's task to handle 404.

Got it. I don't think this is documented anywhere, and  `app.render()` always returns a valid `Response` object - so I assumed it handles the request just fine. Reading through [the source code for `app.render`](
https://github.com/withastro/astro/blob/9f6453cf4972ac28eec4f07a1373feaa295c8864/packages/astro/src/core/app/index.ts#L190), it looks like I can check on the result of `app.match`. If it's `null`, we know that it's a 404 and we can serve the static page.

> For the question of dynamic or static 404 it should be up to the user. If the user uses export const prerender = true;, it should be static. IIRC a 404.html should be generated in the "output" folder. In theory that should be "routable" by Netlify without hitting the ssr function, at least it is with Cloudflare.

I'm assuming that a dynamic 404 page is correctly handled by `app.render`, and the adapter only needs to handle the static case. Netlify Functions, once called, can't pass through the request to the CDN again like on Cloudflare - but I think we can make this work by embedding the static 404 page into the function. (Edge Functions would be able to do this, but we don't use them in the Adapter for other reasons as you're aware)

**Comment by lilnasy** [comment] 2024-01-29 14:33
Is there something preventing the 404.html catch-all being added? It would match the behavior with vercel as well.

**Comment by Skn0tt** [comment] 2024-01-29 14:43
Well, the big blocker for that fallback is the precedence behaviour I outlined. Essentially, you can only ever have one fallback route configured, and in the current design that's the SSR handler. In the Vercel adapter, the SSR handler isn't treated as fallback, but is only assigned to the routes where it will be running on. That makes the adapter a little more complicated, but allows the 404 site to be the fallback.

I'll provide a PR this week that ensures the customer-written 404 pages is shown properly. Then we can continue to think about if it's a problem that that page is served by a Function in some cases.

**Comment by Skn0tt** [comment] 2024-01-29 15:07
Well, "this week" came early. Here's the PR: https://github.com/withastro/adapters/pull/143

**Comment by alexanderniebuhr** [comment] 2024-02-16 07:27
@Skn0tt Can this issue be fixed?

**Comment by Skn0tt** [comment] 2024-02-16 08:40
It's fixed, yes!

**Closed** 2024-02-16 09:28 UTC
Labels: pkg: netlify
