### ISSUE TITLE
Unable to start dev with Cloudflare adapter: `file already exists, mkdir './node_modules/.astro/'`

### ISSUE THREAD

**Issue by peterhirn** [withastro/adapters#151] opened 2024-02-04 09:39 UTC
### Astro Info

```block
Astro                    v4.3.2
Node                     v21.6.1
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
```

### Describe the Bug

Running `pnpm dev` stopped working, produces the following output (replaced absolute project path with '...')

```
10:31:45 [WARN] The currently selected adapter `@astrojs/cloudflare` is not compatible with the image service "Sharp".

 astro  v4.3.2 ready in 310 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

10:31:45 watching for file changes...
10:31:47 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
Error: EEXIST: file already exists, mkdir '/.../node_modules/.astro/'
    at mkdirSync (node:fs:1382:26)
    at LocalPagesRuntime.getCF (file:///.../node_modules/.pnpm/@astrojs+cloudflare@9.0.0_astro@4.3.2/node_modules/@astrojs/cloudflare/dist/utils/local-runtime.js:114:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async middleware (file:///.../node_modules/.pnpm/@astrojs+cloudflare@9.0.0_astro@4.3.2/node_modules/@astrojs/cloudflare/dist/index.js:67:36)
  Hint:
    Make sure your promises all have an `await` or a `.catch()` handler.
  Error reference:
    https://docs.astro.build/en/reference/errors/unhandled-rejection/
  Stack trace:
    at mkdirSync (node:fs:1382:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    [...] See full stack trace in the browser, or rerun with --verbose.
```

### What's the expected result?

`pnpm dev` works

### Workaround

Removing the directory fixes the problem permanently: `rm -r node_modules/.astro/`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment] 2024-02-04 18:14
Thanks for reporting this issue, can you provide a minimal reproduction?

**Comment by alexanderniebuhr** [comment] 2024-02-05 09:18
Thanks for the response.
I got confused because in another branch that check already exists, it is just not merged yet. So the fix is already done, but needs to be released. I'll do that later

**Closed** 2024-02-17 06:03 UTC
Labels: pkg: cloudflare, - P2: has workaround
