### ISSUE TITLE
"npm run dev" is not working with Cloudflare/Astro adapter

### ISSUE THREAD

**Issue by plustra** [withastro/adapters#332] opened 2024-07-17 09:10 UTC
### Astro Info

```block
Astro                    v4.11.5
Node                     v20.15.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
```

### Describe the Bug

I have recently created an **astro/cloudflare** project following the guidelines in the [cloudflare pages frameworks guides](https://developers.cloudflare.com/pages/framework-guides/deploy-an-astro-site/) and when I try to run the `npm run dev` command (which runs the `astro dev` command underneath) I get this error:

```
*** Received structured exception #0xc0000005: access violation; stack: 7ffabe7231f7 7ff6f14494eb 7ff6f14495b3 7ff6f143d1ec 7ff6f143d197 7ff6f0cb832e 7ff6f0cb863f 7ff6efba1706 7ff6efba14ea 7ff6f0e3047f 7ff6f0e37636 7ff6f0e3099c 7ff6f0e37636 7ff6f0e2e30c 7ff6efb91551 7ff6f24cc8df 7ffade2f257c 7ffadf2aaf27
The Workers runtime failed to start. There is likely additional logging output above.
  Stack trace:
    at #assembleAndUpdateConfig (C:\Users\Plustra\Projects\test-project\node_modules\miniflare\dist\src\index.js:9178:13)
    at async Mutex.runWith (C:\Users\Plustra\Projects\test-project\node_modules\miniflare\dist\src\index.js:3521:16)
    at async Miniflare2._getProxyClient (C:\Users\Plustra\Projects\test-project\node_modules\miniflare\dist\src\index.js:9359:5)
    at async getPlatformProxy (C:\Users\Plustra\Projects\test-project\node_modules\wrangler\wrangler-dist\cli.js:210786:20)
    at async withTakingALongTimeMsg (file:///C:/Users/Plustra/Projects/test-project/node_modules/astro/dist/integrations/hooks.js:23:18)
```

It does not happen with all commands, `wrangler types` command work, but other command that trigger a similar error would be `wrangler d1 migrations apply ...`.

- I have changed the Node JS version from using the latest (22.4.1) to the most recent LTS mentioned in the astro info, both of them isntalled via the [prebuilt installer.](https://nodejs.org/en/download/prebuilt-installer) Nothing changed.

- I changed the installed wrangler version of the project from 3.64.0 (latest version) to 3.63.0 (previous version). Nothing changed.

A curiosity about this problem is that I have created projects before using this same stack (astro/cloudflare) and it worked, no more than two months ago I didn't have this problem, I don't have those projects anymore, but I have only received this error in this most recent attempt to create a project.

### What's the expected result?

Previously, in other projects similar to this one I have not had this problem and I have used exactly the same configurations and integrations, so the expected output is to be able to run a development server as in pasts proyects.

### Link to Minimal Reproducible Example

unknown

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment] 2024-07-17 09:22
Duplicate of https://github.com/withastro/adapters/issues/322

_(It's an upstream issue in Cloudflare)_

**Closed by alexanderniebuhr** 2024-07-17 09:22 UTC

**Comment by bot1131357** [comment] 2024-07-18 01:16
Thanks. I have the same issue when I run `npm run dev` with Nuxt. Hopefully it's fixed soon.
