### ISSUE TITLE
Default Astro 404 page does not render on Netlify in production

### ISSUE THREAD

**Issue by whitep4nth3r** [withastro/adapters#291] opened 2024-06-20 08:44 UTC
### Astro Info

```block
Astro                    v4.10.3
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             none
```

## The Astro default 404 page does not render on Netlify in production.

The HTTP status code returned is actually `(failed) net::ERR_HTTP_RESPONSE_CODE_FAILURE`.

![image](https://github.com/withastro/adapters/assets/52798353/18d2b9b6-8196-4841-bba8-a8103db6c5e9)

I noticed this happening on another project of mine. To test that it wasn't just that specific project, I created a brand new Astro repo today, installed the Netlify adapter, and deployed (with no further code changes):

## Example page
[https://test-default-404.netlify.app/asd](https://test-default-404.netlify.app/asd)

## Repo
[https://github.com/whitep4nth3r/test-default-404](https://github.com/whitep4nth3r/test-default-404)

### Notes: 

- The correct Astro 404 page renders in local development using the Netlify CLI.
- I can't get the Netlify CLI to serve the project locally to replicate production, and I submitted a bug report about that.
- **I can replicate the same behaviour (404 not rendering) locally using the node adapter, running `astro build` and then `astro preview`.**
- In either project (the real project and the linked test project), **I am not using a custom 404 page**.

### What's the expected result?

The HTTP response status code returned should be 404 and the Astro default 404 page should render.

### Link to Minimal Reproducible Example

https://test-default-404.netlify.app/asd

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by serhalp** [comment] 2024-07-15 18:07
Thanks for reporting this, @whitep4nth3r! I appreciate the detailed bug report and reproduction steps.

> I can replicate the same behaviour (404 not rendering) locally using the node adapter, running astro build and then astro preview.

I can confirm this isn't specific to Netlify. You can reproduce this issue (a 404 status code with no body, instead of the default Astro 404 page) multiple ways:
- `astro build && astro preview` with the node adapter
- `netlify serve` with the netlify adapter (you'll just need to create a `netlify.toml` for this to work)
- deploying to Netlify with the netlify adapter

I would imagine this means there's a bug in Astro core, or possibly in the template used by `npm create astro`. You may want to transfer this issue to another repo.

Let us know if Netlify can help!

**Comment by serhalp** [comment] 2024-07-15 21:42
@ascorbic Do you know if this is a known issue? I couldn't find anything matching, but this seems like a pretty common setup (create from starter + `astro preview` or deploy to Netlify + get a 404) which I'm finding strange.

**Comment by delucis** [comment] 2024-07-16 21:57
Thanks for the detailed issue @whitep4nth3r — appreciate it!

This is actually working “as expected”, although maybe we can do something to make it _more_ expected than it felt for you 😀

Here’s what’s happening:

- The default 404 you see in dev is intended to _only_ display during development. For example, it lets us suggest where to go if someone visits `/` with the `base` option set. But we don’t ever build it out for production.

- In static sites, this usually means that when there’s no custom 404, the host’s 404 page will show. (For example, on Netlify you’d get their standard 404 page.)

- But when using an adapter, the Astro serverless function will always handle the request, so it never makes it through to Netlify’s default 404 page.

The way I’ve always thought of it, it would be kind of “rude” for Astro to intervene and add a default 404 that advertises itself. And there’s also a bit of complexity, because OK, we could decide that the above is a bad experience, best to add a default, but then… should we also add a default for static sites? Even though that would then override a host’s default 404? Less clear.

Maybe what would be best here could be to make it more obvious that our dev server 404 is _only_ present during dev? Definitely open to ideas!

In the meantime, hope you don’t mind me closing this as not technically a bug.

**Closed by delucis** 2024-07-16 21:57 UTC
Labels: pkg: netlify

**Comment by whitep4nth3r** [comment] 2024-07-17 07:55
Thanks @delucis — that makes sense! 

Some thoughts:

- I wonder if there's a way to work with Netlify to fall through to the Netlify 404 somehow when there's no custom 404 provided in the repo (that being said, this is just to solve the very niche problem of getting Sentry errors when there is no custom 404, and really, people using Sentry are going to have a custom 404, so perhaps this is moot)

- To help people understand how this works in the future, perhaps the default Astro 404 that is present in dev only should contain a small message saying that you won't see it in production (this would have massively helped me and also not wasted your time with this bug report [😅], and yes it makes sense that you don't want to advertise Astro in production.)

**Comment by ascorbic** [comment] 2024-07-17 08:35
I think 1 may be tough. However we should definitely do 2, along with including it in the docs somewhere. I'd also add that I think that just a bit of text saying "Not Found" rather than a blank page would help.
